-- CLOSR 운영 스키마
--
-- 운영 프로필은 ddl-auto: validate 라 애플리케이션이 테이블을 만들지 않습니다.
-- 첫 배포 전에 이 파일을 DB 에 적용해야 기동에 성공합니다.
--
--   docker exec -i closr-db psql -U closr -d closr < db/schema.sql
--
-- 여러 번 실행해도 안전합니다 (IF NOT EXISTS).
-- 엔티티를 바꾸면 이 파일도 함께 고쳐야 합니다. 로컬에서 확인하는 방법:
--   docker exec closr-db pg_dump -U closr -d closr --schema-only --no-owner

-- 게스트 세션. 회원 개념이 없어 아바타와 피팅 결과를 여기에 매답니다.
CREATE TABLE IF NOT EXISTS sessions (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token varchar(64)  NOT NULL,
    expires_at    timestamp(6) NOT NULL,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    CONSTRAINT uk_sessions_token UNIQUE (session_token)
);

-- 피팅룸에서 고를 수 있는 의류. 현재 6종.
CREATE TABLE IF NOT EXISTS garments (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design        varchar(50)  NOT NULL,
    name          varchar(100) NOT NULL,
    category      varchar(30)  NOT NULL,
    -- 슬림 · 레귤러 · 오버핏. 허용 편차 범위를 이 값으로 찾습니다.
    fit           varchar(20),
    -- 이미지가 아직 없어 시드에서는 비워 둡니다.
    thumbnail_url varchar(500),
    purchase_url  varchar(500),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    CONSTRAINT uk_garments_design UNIQUE (design)
);

-- 사진 1장으로 만든 3D 아바타.
-- measurements 는 부위 구성이 바뀔 수 있어 jsonb 로 둡니다.
CREATE TABLE IF NOT EXISTS avatars (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   bigint       NOT NULL,
    job_id       varchar(64),
    status       varchar(20)  NOT NULL,
    height_cm    integer,
    weight_kg    integer,
    glb_url      varchar(500),
    measurements jsonb,
    warnings     jsonb,
    confidence   double precision,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    CONSTRAINT fk_avatars_session FOREIGN KEY (session_id) REFERENCES sessions (id)
);

-- 의류 한 벌의 사이즈별 실측 스펙.
-- 스펙 확정 전이라 시드 데이터가 없습니다.
CREATE TABLE IF NOT EXISTS garment_size_specs (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garment_id   bigint       NOT NULL,
    size         varchar(10)  NOT NULL,
    measurements jsonb,
    -- 부위별 목표 여유. 판정은 실제 여유가 아니라 이 값 대비 편차로 합니다.
    target_ease  jsonb,
    model_url    varchar(500),
    created_at   timestamp(6),
    updated_at   timestamp(6),
    CONSTRAINT uk_garment_size UNIQUE (garment_id, size),
    CONSTRAINT fk_garment_size_specs_garment FOREIGN KEY (garment_id) REFERENCES garments (id)
);

-- PostgreSQL 은 외래키 컬럼에 인덱스를 자동으로 만들지 않습니다.
-- 조회가 이 방향으로 일어나므로 명시적으로 만들어 둡니다.
CREATE INDEX IF NOT EXISTS idx_avatars_session ON avatars (session_id);
CREATE INDEX IF NOT EXISTS idx_garment_size_specs_garment ON garment_size_specs (garment_id);

-- 피팅 결과 기록. 사용자가 본 결과를 그대로 남겨 다시 열어볼 수 있게 합니다.
-- result 에 응답 전체를 담습니다. 판정 기준이 바뀌어도 그때 본 화면이 나와야 합니다.
CREATE TABLE IF NOT EXISTS fitting_records (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       bigint      NOT NULL,
    avatar_id        bigint      NOT NULL,
    garment_id       bigint      NOT NULL,
    recommended_size varchar(10),
    wearable         boolean     NOT NULL,
    result           jsonb       NOT NULL,
    created_at       timestamp(6),
    updated_at       timestamp(6),
    CONSTRAINT fk_fitting_records_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_fitting_records_avatar  FOREIGN KEY (avatar_id)  REFERENCES avatars (id),
    CONSTRAINT fk_fitting_records_garment FOREIGN KEY (garment_id) REFERENCES garments (id)
);

-- 목록은 세션별 최신순으로 읽습니다.
CREATE INDEX IF NOT EXISTS idx_fitting_records_session
    ON fitting_records (session_id, created_at DESC);

-- 핏 · 부위별 허용 편차 범위.
-- 핏에만 종속되어 의류가 늘어도 이 표는 그대로입니다.
CREATE TABLE IF NOT EXISTS fit_tolerances (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fit        varchar(20) NOT NULL,
    part       varchar(30) NOT NULL,
    dev_min    double precision NOT NULL,
    dev_max    double precision NOT NULL,
    created_at timestamp(6),
    updated_at timestamp(6),
    CONSTRAINT uk_fit_tolerance UNIQUE (fit, part)
);

CREATE TABLE IF NOT EXISTS garment_likes (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  bigint  NOT NULL REFERENCES sessions(id),
    garment_id  bigint  NOT NULL REFERENCES garments(id),
    created_at  timestamp(6),
    updated_at  timestamp(6),
    CONSTRAINT uk_garment_likes_session_garment UNIQUE (session_id, garment_id)
    );

CREATE INDEX IF NOT EXISTS idx_garment_likes_session ON garment_likes(session_id);

-- AI 챗봇 대화.
-- LLM API 는 무상태라 매 턴마다 이전 대화를 다시 보내야 합니다. 그 히스토리를
-- 여기에 보관합니다. AI 서버는 프로세스 메모리만 쓰므로 재시작하면 사라집니다.
CREATE TABLE IF NOT EXISTS conversations (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id varchar(40) NOT NULL UNIQUE,
    session_id      bigint      NOT NULL,
    mode            varchar(20) NOT NULL,
    avatar_id       bigint,
    -- 대화에서 뽑은 요약. 다음 요청의 fit_context.profile 로 되돌려 보냅니다.
    -- 항목이 고정돼 있어(용도 · 신경쓰는부위 · 선호핏 · 피하는것) 자유 서술이 들어오지 않습니다.
    summary         jsonb,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    CONSTRAINT fk_conversations_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_conversations_avatar  FOREIGN KEY (avatar_id)  REFERENCES avatars (id)
);

-- 대화 메시지. 사용자 발화와 챗봇 답변을 role 로 구분해 같은 표에 담습니다.
-- LLM API 가 요구하는 형태와 같아 변환 없이 그대로 보낼 수 있습니다.
CREATE TABLE IF NOT EXISTS chat_messages (
    id              bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id      varchar(40) NOT NULL UNIQUE,
    conversation_id bigint      NOT NULL,
    role            varchar(20) NOT NULL,
    content         text        NOT NULL,
    created_at      timestamp(6),
    updated_at      timestamp(6),
    CONSTRAINT fk_chat_messages_conversation
        FOREIGN KEY (conversation_id) REFERENCES conversations (id)
);

-- 화면 복원은 대화별 오래된 순, AI 전달은 최신순으로 읽습니다.
CREATE INDEX IF NOT EXISTS idx_chat_messages_conversation
    ON chat_messages (conversation_id, id);
