-- CLOSR 운영 스키마
--
-- 운영 프로필은 ddl-auto: validate 라 애플리케이션이 테이블을 만들지 않습니다.
-- 첫 배포 전에 이 파일을 DB 에 적용해야 기동에 성공합니다.
--
--   docker exec -i closr-db psql -U closr -d closr < db/schema.sql
--
-- 여러 번 실행해도 안전합니다 (IF NOT EXISTS).
-- 엔티티를 바꾸면 이 파일도 함께 고쳐야 합니다. 로컬에서 확인하는 방법:
--   docker exec closr-db pg_dump -U closr -d closr --schema-only --no-owner

-- 게스트 세션. 회원 개념이 없어 아바타와 피팅 결과를 여기에 매답니다.
CREATE TABLE IF NOT EXISTS sessions (
    id            bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token varchar(64)  NOT NULL,
    expires_at    timestamp(6) NOT NULL,
    created_at    timestamp(6),
    updated_at    timestamp(6),
    CONSTRAINT uk_sessions_token UNIQUE (session_token)
);

-- 피팅룸에서 고를 수 있는 의류. 현재 6종.
CREATE TABLE IF NOT EXISTS garments (
    id         bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design        varchar(50)  NOT NULL,
    name          varchar(100) NOT NULL,
    category      varchar(30)  NOT NULL,
    -- 이미지가 아직 없어 시드에서는 비워 둡니다.
    thumbnail_url varchar(500),
    created_at    timestamp(6),
    updated_at    timestamp(6),
    CONSTRAINT uk_garments_design UNIQUE (design)
);

-- 사진 1장으로 만든 3D 아바타.
-- measurements 는 부위 구성이 바뀔 수 있어 jsonb 로 둡니다.
CREATE TABLE IF NOT EXISTS avatars (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   bigint       NOT NULL,
    job_id       varchar(64),
    status       varchar(20)  NOT NULL,
    height_cm    integer,
    weight_kg    integer,
    glb_url      varchar(500),
    measurements jsonb,
    confidence   double precision,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    CONSTRAINT fk_avatars_session FOREIGN KEY (session_id) REFERENCES sessions (id)
);

-- 의류 한 벌의 사이즈별 실측 스펙.
-- 스펙 확정 전이라 시드 데이터가 없습니다.
CREATE TABLE IF NOT EXISTS garment_size_specs (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garment_id   bigint       NOT NULL,
    size         varchar(10)  NOT NULL,
    measurements jsonb,
    model_url    varchar(500),
    created_at   timestamp(6),
    updated_at   timestamp(6),
    CONSTRAINT uk_garment_size UNIQUE (garment_id, size),
    CONSTRAINT fk_garment_size_specs_garment FOREIGN KEY (garment_id) REFERENCES garments (id)
);

-- PostgreSQL 은 외래키 컬럼에 인덱스를 자동으로 만들지 않습니다.
-- 조회가 이 방향으로 일어나므로 명시적으로 만들어 둡니다.
CREATE INDEX IF NOT EXISTS idx_avatars_session ON avatars (session_id);
CREATE INDEX IF NOT EXISTS idx_garment_size_specs_garment ON garment_size_specs (garment_id);
